import { Inter } from 'next/font/google'
import './globals.css'
import StyledComponentsRegistry from '@/components/AntdRegistry'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Lab3',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + ' bg-blue-50'}>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
